// RebaseTodoApp — the git-rebase-todo custom editor UI (boot mode 'todo').
// Visual planner for an interactive rebase started in a terminal: reorder by
// drag, choose pick/reword/edit/squash/fixup/drop per commit, then save+close
// so git resumes — or abort by emptying the todo. Shares the exact visual
// language (and CSS) of RebaseProgress — the "Rebase en cours" tab that
// auto-opens for the very same rebase and can be visible side by side.

import React, { useState, useEffect, useRef, useCallback } from 'react'
import { useLang } from '../../../src/renderer/src/i18n/LanguageContext'
import '../../../src/renderer/src/components/RebaseProgress/RebaseProgress.css'

declare global { interface Window { gitAPI: any } }

type TodoAction = 'pick' | 'reword' | 'edit' | 'squash' | 'fixup' | 'drop'
const ACTIONS: TodoAction[] = ['pick', 'reword', 'edit', 'squash', 'fixup', 'drop']
const SHORTCUT_KEYS: Record<string, TodoAction> = {
  p: 'pick', r: 'reword', e: 'edit', s: 'squash', f: 'fixup', d: 'drop',
}

const ACTION_COLORS: Record<string, string> = {
  pick: '#3fb950',
  reword: '#58a6ff',
  edit: '#58a6ff',
  squash: '#d2a8ff',
  fixup: '#ffa657',
  drop: '#f85149',
}

// Long action names as generated by git; single-letter aliases just in case.
const ACTION_ALIASES: Record<string, TodoAction> = {
  p: 'pick', r: 'reword', e: 'edit', s: 'squash', f: 'fixup', d: 'drop',
  pick: 'pick', reword: 'reword', edit: 'edit', squash: 'squash', fixup: 'fixup', drop: 'drop',
}

interface TodoEntry {
  id: number
  kind: 'commit' | 'directive'
  action: string          // TodoAction for commits; raw keyword for directives
  hash: string
  shortHash: string
  rest: string            // everything after the hash (subject, possibly "# subject")
  raw: string             // original line, used verbatim for directives
}

function parseTodo(text: string): TodoEntry[] {
  const entries: TodoEntry[] = []
  let id = 0
  for (const line of text.split('\n')) {
    const t = line.trim()
    if (!t || t.startsWith('#')) continue
    const m = t.match(/^([a-zA-Z]+)\s+([0-9a-f]{7,40})(?:\s+(.*))?$/)
    const action = m ? ACTION_ALIASES[m[1].toLowerCase()] : undefined
    if (m && action) {
      entries.push({
        id: id++, kind: 'commit', action, hash: m[2],
        shortHash: m[2].slice(0, 7), rest: m[3] ?? '', raw: t,
      })
    } else {
      // exec / break / label / reset / merge / update-ref / noop …
      entries.push({ id: id++, kind: 'directive', action: t.split(/\s+/)[0], hash: '', shortHash: '', rest: '', raw: t })
    }
  }
  return entries
}

function serializeTodo(entries: TodoEntry[]): string {
  const lines = entries.map(e =>
    e.kind === 'commit'
      ? `${e.action} ${e.hash}${e.rest ? ' ' + e.rest : ''}`
      : e.raw
  )
  return lines.join('\n') + '\n'
}

export default function RebaseTodoApp() {
  const { t } = useLang();

  const [entries, setEntries] = useState<TodoEntry[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [headName, setHeadName] = useState('')
  const [ontoShort, setOntoShort] = useState('')
  const dragIndex = useRef<number | null>(null)
  const [dragOver, setDragOver] = useState<number | null>(null)

  useEffect(() => {
    window.gitAPI.todoGet()
      .then((r: { text: string }) => { setEntries(parseTodo(r?.text ?? '')); setLoading(false) })
      .catch(() => { setError('Impossible de lire le fichier de rebase'); setLoading(false) })
    // Best-effort — only used for the same branch/onto ref chips the
    // "Rebase en cours" tab shows; harmless if this ever comes back empty.
    window.gitAPI.getRebaseState?.().then((s: any) => {
      if (s?.headName) setHeadName(s.headName)
      if (s?.ontoShort) setOntoShort(s.ontoShort)
    }).catch(() => { /* cosmetic only */ })
  }, [])

  const setAction = (i: number, action: TodoAction) => {
    setEntries(prev => prev.map((e, idx) => idx === i ? { ...e, action } : e))
  }

  const moveEntry = (from: number, to: number) => {
    if (to < 0 || to >= entries.length || from === to) return
    setEntries(prev => {
      const arr = [...prev]
      const [item] = arr.splice(from, 1)
      arr.splice(to, 0, item)
      return arr
    })
  }

  const handleRowKeyDown = (e: React.KeyboardEvent, i: number) => {
    const key = e.key.toLowerCase()
    if (e.altKey && (key === 'arrowup' || key === 'arrowdown')) {
      e.preventDefault()
      moveEntry(i, key === 'arrowup' ? i - 1 : i + 1)
      return
    }
    if (entries[i].kind === 'commit' && SHORTCUT_KEYS[key]) {
      e.preventDefault()
      setAction(i, SHORTCUT_KEYS[key])
    }
  }

  const handleDragStart = (i: number) => { dragIndex.current = i }
  const handleDragOver = (e: React.DragEvent, i: number) => { e.preventDefault(); setDragOver(i) }
  const handleDrop = (target: number) => {
    const from = dragIndex.current
    if (from === null || from === target) { setDragOver(null); return }
    moveEntry(from, target)
    dragIndex.current = null
    setDragOver(null)
  }

  const commits = entries.filter(e => e.kind === 'commit')
  const firstKeptIndex = entries.findIndex(e => e.kind === 'commit' && e.action !== 'drop')

  const handleLaunch = useCallback(async () => {
    const firstKept = entries.find(e => e.kind === 'commit' && e.action !== 'drop')
    if (firstKept && (firstKept.action === 'squash' || firstKept.action === 'fixup')) {
      setError(t('ir.firstKept'))
      return
    }
    setError(null)
    await window.gitAPI.todoSave(serializeTodo(entries))
  }, [entries])

  const handleAbort = useCallback(async () => {
    const ok = await window.gitAPI.uiConfirm('Abandonner le rebase interactif ?')
    if (ok) await window.gitAPI.todoAbort()
  }, [])

  return (
    <div className="rp-page">
      <div className="rp-header">
        <div className="rp-header-top">
          <span className="rp-title">⚡ Rebase interactif</span>
        </div>
        <div className="rp-header-refs">
          {headName && <span className="rp-ref-chip"><span className="rp-ref-icon">⑂</span>{headName}</span>}
          {headName && ontoShort && <span className="rp-ref-onto">onto</span>}
          {ontoShort && (
            <span className="rp-ref-chip rp-ref-chip--commit"><span className="rp-ref-icon">◈</span>{ontoShort}</span>
          )}
          <span className="rp-header-spring" />
          <span className="rp-counter">{commits.length} commit{commits.length > 1 ? 's' : ''}</span>
        </div>
      </div>

      {error && (
        <div className="rp-banner rp-banner--conflict">
          <span className="rp-banner-icon">⚠️</span>
          <span className="rp-banner-text">{error}</span>
        </div>
      )}

      <div className="rp-steps">
        {loading && <div className="rp-empty">Chargement…</div>}
        {!loading && entries.length === 0 && <div className="rp-empty">{t('ext.rebase.empty')}</div>}
        {entries.map((entry, i) => (
          <div
            key={entry.id}
            className={`rp-step rp-step--editable ${dragOver === i ? 'drag-over' : ''}`}
            tabIndex={0}
            draggable
            onDragStart={() => handleDragStart(i)}
            onDragOver={e => handleDragOver(e, i)}
            onDrop={() => handleDrop(i)}
            onDragEnd={() => setDragOver(null)}
            onKeyDown={e => handleRowKeyDown(e, i)}
          >
            <span className="rp-step-drag" title={t('ext.rebase.drag')}>⠿</span>
            {entry.kind === 'commit' ? (
              <>
                <select
                  className="rp-step-select"
                  value={entry.action}
                  onChange={e => setAction(i, e.target.value as TodoAction)}
                  style={{ color: ACTION_COLORS[entry.action] ?? '#e6edf3' }}
                >
                  {ACTIONS.map(a => (
                    <option key={a} value={a}
                      disabled={i === firstKeptIndex && (a === 'squash' || a === 'fixup')}>
                      {a}
                    </option>
                  ))}
                </select>
                <span className="rp-step-subject">{entry.rest.replace(/^#\s*/, '')}</span>
                <span className="rp-step-spring" />
                <code className="rp-step-hash">◈ {entry.shortHash}</code>
              </>
            ) : (
              <code className="rp-step-directive">{entry.raw}</code>
            )}
          </div>
        ))}
      </div>

      <div className="rp-legend">
        {t('ext.rebase.help')}
      </div>

      <div className="rp-footer">
        <button className="rp-btn rp-btn--abort" onClick={handleAbort}>Abandonner</button>
        <span className="rp-footer-spring" />
        <button className="rp-btn rp-btn--continue" onClick={handleLaunch} disabled={loading || entries.length === 0}>
          ⚡ Lancer le rebase
        </button>
      </div>
    </div>
  )
}
